{{- if not .Values.existingToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "discord-bot-cryptoprices.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "discord-bot-cryptoprices.labels" . | nindent 4 }}
type: Opaque
data:
  TOKEN: {{ .Values.token | b64enc | quote }}
{{- end }}
