apiVersion: v1
kind: Service
metadata:
  name: cluster-orch
  namespace: kube-system
  labels:
    {{- include "harness-ccm-cluster-orchestrator.operator.selectorLabels" . | nindent 4 }}
spec:
  ports:
  - port: 8753
    protocol: TCP
  selector:
    {{- include "harness-ccm-cluster-orchestrator.operator.selectorLabels" . | nindent 4 }}