{{- if not .Values.existingApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: harness-api-key
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-cluster-orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.apiToken }}
{{- end }}