{{- if .Values.discoveryServiceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harness-ccm-autostopping.discoveryServiceAccountName" . }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
  {{- with .Values.discoveryServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
