apiVersion: apps/v1
kind: Deployment
metadata:
  # name: {{ include "harness-ccm-autostopping.progressAgent.name" . }}
  name: progress-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harness-ccm-autostopping.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "harness-ccm-autostopping.progressAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.progressAgent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "harness-ccm-autostopping.progressAgent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.progressAgent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "harness-ccm-autostopping.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.progressAgent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "harness-ccm-autostopping.progressAgent.name" . }}
          securityContext:
            {{- toYaml .Values.progressAgent.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - 'progress_agent'
          ports:
          - containerPort: 8290
            name: master-port
          env:
          - name : PROGRESS_PAGE_AGENT_PORT
            value : "8290"
          - name : PROGRESS_PAGE_AGENT_PORT_FROM
            value : "8291"
          - name : PROGRESS_PAGE_AGENT_PORT_TO
            value : "8491"
          - name : HARNESS_API
            value: https://{{ .Values.harnessUrl }}/gateway/lw/api
          - name : REMOTE_ACCOUNT_ID
            value : {{ .Values.accountId }}
          resources:
            {{- toYaml .Values.progressAgent.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.progressAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.progressAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.progressAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
